apiVersion: v1
kind: Service
metadata:
  name: orders-microservice
  namespace: ecommerce-namespace
spec:
  selector:
    app: orders-microservice
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070
  type: ClusterIP
