apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: ecommerce-namespace
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: anfimecommerceregistry.azurecr.io/ecommerce-postgres:latest
          env:
            - name: POSTGRES_USER
              value: db
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_DB
              value: ecommerce
          ports:
            - containerPort: 5432
