version: '3.8'
name: ecommerse
services:
  postgres:
    image: postgres:15.6
    ports:
      - "5432:5432"
    volumes:
      - ./local/postgresql:/var/lib/postgresql/data
      - ./local/postgresql/init:/docker-entrypoint-initdb.d
    environment:
      PGDATA: /var/lib/postgresql/data/ecommerse/
      POSTGRES_DB: ecommerse
      POSTGRES_USER: db
      POSTGRES_PASSWORD: 1234
    networks:
      - postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U db -d ecommerse" ]
      interval: 5s
      timeout: 5s
      retries: 5
  
  product-service:
    image: anfim/ecommerce-products:v1.0
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USERNAME: db
      POSTGRES_PASSWORD: 1234
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres
  
  user-service:
    image: anfim/ecommerce-users:v1.0
    ports:
      - "9090:9090"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USERNAME: db
      POSTGRES_PASSWORD: 1234
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres

networks:
  postgres:
    driver: bridge