apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  selector:
    app: myapp # This should match the spec.template.metadata.labels in the deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      